spring:
  application:
    name: KafkaProducer
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  kafka:
    consumer:
      group-id: kafka-call-group
    bootstrap-servers: ubuntu-server:9092
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.apache.kafka.config: ERROR

server:
  port: 8888
  servlet:
    context-path: /
  max-http-header-size: 8KB
  tomcat:
    max-threads: 100
    max-swallow-size: 2MB
    accesslog:
      enabled: true
      prefix: access_log_kafkaproducer
      pattern: "[%A] [%v] [%{yyyy-MM-dd HH:mm:ss}t]  [%a] [%h] [%S] [accesslog] [%m] [%r] [%{User-Agent}i]"
    basedir: E:\access_log
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"